### ISSUE TITLE
[Maps] You need to give name input in order to show a pin in apple maps

### ISSUE THREAD

**Issue by alimoncul** [smartface/sf-extension-utils#102]
This should be documented I think.

https://github.com/smartface/sf-extension-utils/blob/f769939de32e40fc9c2c9b8493b17116f914ebb9/lib/maps/index.d.ts#L43

**Comment by furkanarabaci** [comment]
Due to util-to-native changes, this has been moved to native issues

**Comment by furkanarabaci** [comment]
https://linear.app/smartface/issue/NTVE-390/[maps]-you-need-to-give-name-input-in-order-to-show-a-pin-in-apple
