### ISSUE TITLE
SUPDEV-1168

### ISSUE THREAD

**Issue by muhammedyalcin** [smartface/sf-extension-utils#11]
sf-extension-utils@3.12.1
sf-core@3.0.2-beta.1
Hi,
Customer asking; 
I have an issue for fingerprint. if i firstLogin not accept on fingerprint, it's not show everytime. but i want useFingerprintLogin property set to only false and if i useFingerprintLogin property change to true, it's should be ask 'u want to use fingerprint'

**Comment by alperozisik** [comment]
Developer can use `dataKeys` argument to define custom keys to store information or use the default. Right now it is in default; which is not a problem.

Please check the code https://github.com/smartface/sf-extension-utils/blob/46db8765a92dcff56be0e37883c76f46efe08784/lib/fingerprint.js#L77
As seen in the code, the key values are used there. When there is a need developer can clear or set the data fields
