### ISSUE TITLE
ServiceCall: fullResponse true option doesnt return requestUrl if request is successful

### ISSUE THREAD

**Issue by alimoncul** [smartface/sf-extension-utils#111]
`fullResponse: true`
returns body & statusCode & headers etc. but does not returns the requestUrl.

**Comment by furkanarabaci** [comment]
Since this will be moved to native, a distinct issue will be craeted there #134

**Comment by furkanarabaci** [comment]
New issue: https://linear.app/smartface/issue/NTVE-389/servicecall-fullresponse-true-option-doesnt-return-requesturl-if
