### ISSUE TITLE
Chai as a peerDependencies

### ISSUE THREAD

**Issue by cenkce** [smartface/sf-extension-utils#8]
Should Chai be in devDependencies? Because When I develop a project, I don't need to test sf-extension-utils. But this module install for every project and It is able to create conflict.

**Comment by alperozisik** [comment]
Chai is implemented as runtime type checking
If you have any other alternative suggestions, I am open to that.
Also, chai version in peer dependency it is not fixed, so you may use an incremented version

**Comment by alperozisik** [comment]
@cenkce if you are satisfied with the answer please close the issue. Otherwise, I am going to close it at the end of the week.

**Comment by cenkce** [comment]
I think it fits very weel. https://github.com/zertosh/invariant

**Comment by alperozisik** [comment]
No more chai dependency since v4.0.0
